#!/usr/bin/env bash
#
# This script get the keystore and truststore from secret file generated by the cert manager
#
# ./scripts/get_store.sh
#
# Example:
# PASSWORD=supersecret ./scripts/get_store.sh

TEMP_DIR="_temp"
PASSWORD=${PASSWORD:=password}

mkdir -p ${TEMP_DIR}/cert-manager

for VAL in "keystore" "truststore"; do
  echo "========================================================"
  echo "Getting the $VAL.p12 file from the tls-secret"
  echo "======================================================"
  kubectl get secret/tls-secret -n demo -o json | jq -r .data.\"${VAL}.p12\" | base64 -d - > ${TEMP_DIR}/cert-manager/${VAL}.p12

  echo "Reading the $VAL.p12"
  echo "================================================"
  openssl pkcs12 -info -in ${TEMP_DIR}/cert-manager/${VAL}.p12 -passin pass:${PASSWORD} -passout pass:${PASSWORD}
done

