#!/usr/bin/env bash
#
# This script get the keystore and truststore from secret file generated by the cert manager
#
# ./scripts/get_store.sh
#
# Example:
# STORE_PASSWORD=supersecret ./scripts/get_store.sh

TEMP_DIR="_temp"
STORE_PASSWORD=${STORE_PASSWORD:=password}
NAMESPACE=${NAMESPACE:=demo}
HOSTNAME=${HOSTNAME:-localhost}

mkdir -p ${TEMP_DIR}/cert-manager

for VAL in "keystore" "truststore"; do
  echo "========================================================"
  echo "Getting the $VAL.p12 file from the tls-secret"
  echo "======================================================"
  kubectl get secret/${HOSTNAME}-tls -n ${NAMESPACE} -o json | jq -r .data.\"${VAL}.p12\" | base64 -d - > ${TEMP_DIR}/cert-manager/${VAL}.p12

  echo "Reading the $VAL.p12"
  echo "================================================"
  openssl pkcs12 -info -in ${TEMP_DIR}/cert-manager/${VAL}.p12 -passin pass:${STORE_PASSWORD} -passout pass:${STORE_PASSWORD}
done

